name: Storage Unit and Integration test

on:
  push:
    branches:
    - main
    - storage_pipe_test
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 45
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run Integration test
      working-directory: ./build/storage/tests/it
      run: |
        chmod -R 777 run.sh
        sudo modprobe kvm-intel
        ./run.sh 
