name: Storage Unit and Integration test

on:
  push:
    branches:
    - main
    - storage_pipe_test
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run UT
      working-directory: ./build/storage/tests/ut
      run: |
        chmod -R 777 run.sh
        ./run.sh
