---
name: 'Storage Unit Tests Integration'

on:
  pull_request:
    branches:
      - main
      - black_bandit
    paths:
      - 'build/storage/**'
      - '.github/workflows/storage-ci.yml'
  push:
    branches:
      - main
      - black_bandit
    paths:
      - 'build/storage/**'
      - '.github/workflows/storage-ci.yml'

concurrency:
  # if workflow for PR or push is already running stop it, and start new one
  group: storage-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  py_black_test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: Copy host target files
        working-directory: ./build/storage/core
        run: |
          cp -r host-target ../../../
        
      - name: black test
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./host-target/"
          version: "22.10.0"
          jupyter: true
          
  py_bandit_test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      
    - name: 'Checkout'
      uses: actions/checkout@v3
        
    - name: Run bandit
      uses: tj-actions/bandit@v5.1
      with:
        targets: |  # or a single string "." 
          ./build/storage/core/host-target/
        options: "-r"
